### ISSUE TITLE
Timestamp for the message should be created right after acquiring the image

### ISSUE THREAD

**Issue by tambetm** [UT-ADL/nvidia_gmsl_driver_ros#5]
To facilitate more accurate latency measurement with `rostopic delay`, the [timestamp for camera image](https://github.com/UT-ADL/nvidia_gmsl_driver_ros/blob/main/src/cameras/CameraJpg.cpp#L25) should be created right after acquiring the image, not before publishing the message.

**Comment by MaxandreOgeret** [comment]
The timestamp is captured [here](https://github.com/UT-ADL/nvidia_gmsl_driver_ros/blob/main/src/cameras/CameraBase.cpp#L103), and is extracted from the image handle right after the image is acquired.

It wouldn't make any difference to move the ros timestamp calculation  earlier in the camera pipeline. 

If you think it's clearer to store the ros timestamp directly as `CameraBase` class member I can do that.

**Comment by tambetm** [comment]
Thanks, this escaped my attention.
