### ISSUE TITLE
Error from 'map_msgs' 

### ISSUE THREAD

**Issue by TESLA8KIM** [UT-ADL/nvidia_gmsl_driver_ros#6]
Hello, I'm installing about your instruction at the HOST PC, but there's error and it's really hard to manage it. 
So can you give me any comments?
Thanks.

**--------Error---------**

<== Finished processing package [194 of 238]: 'map_msgs'

==> Processing catkin package: 'nvidia_gmsl_driver_ros'
==> Building with env: '/home/glad/ros_catkin_ws/devel_isolated/map_msgs/env.sh'
==> cmake /home/glad/ros_catkin_ws/src/nvidia_gmsl_driver_ros -DCATKIN_DEVEL_PREFIX=/home/glad/ros_catkin_ws/devel_isolated/nvidia_gmsl_driver_ros -DCMAKE_INSTALL_PREFIX=/home/glad/ros_catkin_ws/install_isolated -G Unix Makefiles in '/home/glad/ros_catkin_ws/build_isolated/nvidia_gmsl_driver_ros'
CMake Warning at cmake/SamplesSetBuildType.cmake:17 (message):
  CMAKE_BUILD_TYPE must be one of (Debug|Release).  Using Release as default.
Call Stack (most recent call first):
  cmake/MainConfiguration.cmake:10 (include)
  CMakeLists.txt:18 (include)

CMake Error at /usr/share/cmake-3.17/Modules/CMakeDetermineCompilerId.cmake:223 (file):
  file failed to open for writing (Permission denied):

/home/glad/ros_catkin_ws/build_isolated/nvidia_gmsl_driver_ros/CMakeFiles/3.17.3/CompilerIdCUDA/CMakeCUDACompilerId.cu
Call Stack (most recent call first):
  /usr/share/cmake-3.17/Modules/CMakeDetermineCompilerId.cmake:234 (CMAKE_DETERMINE_COMPILER_ID_WRITE)
  /usr/share/cmake-3.17/Modules/CMakeDetermineCompilerId.cmake:32 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.17/Modules/CMakeDetermineCUDACompiler.cmake:72 (CMAKE_DETERMINE_COMPILER_ID)
  cmake/MainConfiguration.cmake:42 (enable_language)
  CMakeLists.txt:18 (include)

CMake Error at /usr/share/cmake-3.17/Modules/CMakeDetermineCompilerId.cmake:223 (file):
  file failed to open for writing (Permission denied):

/home/glad/ros_catkin_ws/build_isolated/nvidia_gmsl_driver_ros/CMakeFiles/3.17.3/CompilerIdCUDA/CMakeCUDACompilerId.cu
Call Stack (most recent call first):
  /usr/share/cmake-3.17/Modules/CMakeDetermineCompilerId.cmake:234 (CMAKE_DETERMINE_COMPILER_ID_WRITE)
  /usr/share/cmake-3.17/Modules/CMakeDetermineCompilerId.cmake:32 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.17/Modules/CMakeDetermineCUDACompiler.cmake:72 (CMAKE_DETERMINE_COMPILER_ID)
  cmake/MainConfiguration.cmake:42 (enable_language)
  CMakeLists.txt:18 (include)

-- The CUDA compiler identification is unknown
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - broken
CMake Error at /usr/share/cmake-3.17/Modules/CMakeTestCUDACompiler.cmake:46 (message):
  The CUDA compiler

    "/usr/local/cuda/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/glad/ros_catkin_ws/build_isolated/nvidia_gmsl_driver_ros/CMakeFiles/CMakeTmp
    Run Build Command(s):/usr/bin/make cmTC_da6cc/fast && /usr/bin/make  -f CMakeFiles/cmTC_da6cc.dir/build.make CMakeFiles/cmTC_da6cc.dir/build
    make[1]: Entering directory '/home/glad/ros_catkin_ws/build_isolated/nvidia_gmsl_driver_ros/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_da6cc.dir/main.cu.o
    /usr/local/cuda/bin/nvcc  -ccbin=/home/glad/nvidia/nvidia_sdk/DRIVE_OS_5.2.0_SDK_Linux_OS_DRIVE_AGX_XAVIER/DRIVEOS/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++  -I/home/glad/nvidia/nvidia_sdk/DRIVE_OS_5.2.0_SDK_Linux_OS_DRIVE_AGX_XAVIER/DRIVEOS/drive-t186ref-linux/targetfs/../include -I/targets/aarch64-linux/include   -x cu -c /home/glad/ros_catkin_ws/build_isolated/nvidia_gmsl_driver_ros/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_da6cc.dir/main.cu.o
    cc1plus: fatal error: cuda_runtime.h: No such file or directory
    compilation terminated.
    CMakeFiles/cmTC_da6cc.dir/build.make:85: recipe for target 'CMakeFiles/cmTC_da6cc.dir/main.cu.o' failed
    make[1]: *** [CMakeFiles/cmTC_da6cc.dir/main.cu.o] Error 1
    make[1]: Leaving directory '/home/glad/ros_catkin_ws/build_isolated/nvidia_gmsl_driver_ros/CMakeFiles/CMakeTmp'
    Makefile:141: recipe for target 'cmTC_da6cc/fast' failed
    make: *** [cmTC_da6cc/fast] Error 2
    
    

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  cmake/MainConfiguration.cmake:42 (enable_language)
  CMakeLists.txt:18 (include)

-- Configuring incomplete, errors occurred!
See also "/home/glad/ros_catkin_ws/build_isolated/nvidia_gmsl_driver_ros/CMakeFiles/CMakeOutput.log".
See also "/home/glad/ros_catkin_ws/build_isolated/nvidia_gmsl_driver_ros/CMakeFiles/CMakeError.log".
<== Failed to process package 'nvidia_gmsl_driver_ros': 
  Command '['/home/glad/ros_catkin_ws/devel_isolated/map_msgs/env.sh', 'cmake', '/home/glad/ros_catkin_ws/src/nvidia_gmsl_driver_ros', '-DCATKIN_DEVEL_PREFIX=/home/glad/ros_catkin_ws/devel_isolated/nvidia_gmsl_driver_ros', '-DCMAKE_INSTALL_PREFIX=/home/glad/ros_catkin_ws/install_isolated', '-G', 'Unix Makefiles']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /home/glad/ros_catkin_ws/build_isolated/nvidia_gmsl_driver_ros && /home/glad/ros_catkin_ws/devel_isolated/map_msgs/env.sh cmake /home/glad/ros_catkin_ws/src/nvidia_gmsl_driver_ros -DCATKIN_DEVEL_PREFIX=/home/glad/ros_catkin_ws/devel_isolated/nvidia_gmsl_driver_ros -DCMAKE_INSTALL_PREFIX=/home/glad/ros_catkin_ws/install_isolated -G 'Unix Makefiles'

Command failed, exiting.

**Comment by tambetm** [comment]
There are multiple errors, I would suggest to tackle them one-by-one:
1. `file failed to open for writing (Permission denied)` - this is unusual for building something in your home directory. Any chance you used `sudo` during cloning the repo or for build? I would suggest redoing cloning and building from scratch and avoid sudo.
2. `fatal error: cuda_runtime.h: No such file or directory` - this hints for CUDA not being installed. While installation instructions really don't mention CUDA, it might be a oversight from our side. Can you follow [CUDA installation instructions](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) and get back to us if it fixed your error?
