### ISSUE TITLE
Error : No such file or directory  #include <yaml-cpp/yaml.h>           

### ISSUE THREAD

**Issue by TESLA8KIM** [UT-ADL/nvidia_gmsl_driver_ros#8]
<img width="817" alt="error_fatal_h" src="https://user-images.githubusercontent.com/54874733/223721534-e2705579-dd68-4883-a646-08ea8471990b.png">

Hello, Can you give me a advice how to deal with it??
Thanks.

**Comment by TESLA8KIM** [comment]
I resolve that problem

**Comment by cjmodi306** [comment]
@TESLA8KIM hi! I am having the exact same problem. Given that you marked this issue as Closed, I assume you already found the solution to it. Could you please let me know what made it work?

**Comment by tambetm** [comment]
Did you install the build dependencies, especially libyaml-cpp-dev?
```
sudo apt install python-numpy libyaml-cpp-dev python-empy
```

**Comment by cjmodi306** [comment]
> Did you install the build dependencies, especially libyaml-cpp-dev?
> 
> ```
> sudo apt install python-numpy libyaml-cpp-dev python-empy
> ```

Yes I did!
