### ISSUE TITLE
Catkin_make_isolaated Error : cannot find -lyaml-cpp

### ISSUE THREAD

**Issue by TESLA8KIM** [UT-ADL/nvidia_gmsl_driver_ros#9]
I’m doing the ‘catkin_make_isolated’ command to Crossbuild the ROS Workspace to connect the GMSL Camera with Drive Agx Xavier.
**But I just installed the yaml lib(yaml.h) but I’m now facing with ’ -lyaml-cpp’ error.**
Can you give me any advise for this?
Thanks.

<img width="819" alt="lib_yaml_error" src="https://user-images.githubusercontent.com/54874733/223939778-f36c6a0c-1519-4141-b712-2e1be6d4fc2d.png">

**Comment by tambetm** [comment]
Did you install the build dependencies, especially libyaml-cpp-dev?
```
sudo apt install python-numpy libyaml-cpp-dev python-empy
```
